name: genshin_mod_manager
description: Folder-based mod manager. Manage your mods with ease.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.5.12

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  archive: ^4.0.2
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  cp949_codec: ^1.0.2
  desktop_drop: ^0.5.0
  dio: ^5.7.0
  envied: ^1.0.0
  ffi: ^2.1.3
  filepicker_windows: ^2.1.4
  fluent_ui: ^4.9.2
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_hooks: ^0.20.5
  flutter_image_converter: ^0.4.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  hooks_riverpod: ^2.6.1
  http: ^1.2.2
  image_size_getter: ^2.2.0
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0 
  meta: ^1.15.0
  package_info_plus: ^8.1.2
  pasteboard: ^0.3.0
  path: ^1.9.0
  protocol_handler: ^0.2.0
  retrofit: ^4.4.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.4
  smooth_scroll_multiplatform: ^1.0.8
  url_launcher: ^6.3.1
  webview_windows: ^0.4.0
  win32: ^5.9.0
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  dependency_validator: ^4.1.2
  envied_generator: ^1.0.0
  flutter_lints: ^5.0.0
  flutter_oss_licenses: ^3.0.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  plugin_platform_interface: ^2.1.8
  retrofit_generator: ^9.1.5
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  url_launcher_platform_interface: ^2.3.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/
